logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug

wx:
  pay:
    appId: wx754889db206d23c5 #微信公众号或者小程序等的appid
    mchId: 1517156411 #微信支付商户号
    mchKey: hsmyoVjBx1j81ck9caS3GONi34rjynvE #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: classpath:key/apiclient_cert.p12 # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
